spring:
  application:
    name: cassandra

  threads:
    virtual:
      enabled: true

  cassandra:
    password: admin
    username: admin
    schema-action: CREATE_IF_NOT_EXISTS
    contact-points: http://127.0.0.1
    port: 9042
    keyspace-name: phyex0